name: Validate TEI documents

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "tei/*.xml"

jobs:
  validate_tei:
    runs-on: ubuntu-latest
    name: Validate against TEI_all
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Validate
        uses: dracor-org/tei-validate-action@94b08b8bf0dd1810fe7962aa59435b46c769bbcb # v1.2.0
