name: Validate TEI documents

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "tei/*.xml"

jobs:
  validate_tei:
    runs-on: ubuntu-latest
    name: Validate against TEI_all
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Validate
        uses: dracor-org/tei-validate-action@94b08b8bf0dd1810fe7962aa59435b46c769bbcb # v1.2.0
